CLASS LHC_ZABCR_CIT_STU_22AD067123 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZabcrCitStu22ad067123
        RESULT result.
ENDCLASS.

CLASS LHC_ZABCR_CIT_STU_22AD067123 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
